### ISSUE TITLE
建行找不到token值

### ISSUE THREAD

**Issue by yifangyujason** [villagebully8/yybs#1]
如题，按照该请求https://yunbusiness.ccb.com/basic_service/txCtrl? 找请求头中token值，没找到，其他参数都可以找到

**Comment by villagebully8** [comment]
cookie列表应该有 你不一定在 https://yunbusiness.ccb.com/basic_service/txCtrl？中 可以在登录成功后的包里找 大部分包都有这些数据

**Comment by yifangyujason** [comment]
找到了，在yunbusiness.ccb.com/clp_service/txCtrl有，感谢
