### ISSUE TITLE
滴滴果园

### ISSUE THREAD

**Issue by nameyq11** [villagebully8/yybs#3]
滴滴果园，ck 时间超短，只能使用一次，第二次就过期。用其它果园可以正常。是我自己的问题吗？

**Comment by villagebully8** [comment]
是滴滴那边问题，
1.ck在哪个设备抓到就在哪个设备跑任务。比如你在电脑A抓的数据，那么在电脑B跑 数据就会失效。（关系不大）
2.不要在登录滴滴app或者小程序了（1不是重点，关键是这点）
-----
我的就是这样，好几天都没有掉线
