### ISSUE TITLE
云盘出错了大哥

### ISSUE THREAD

**Issue by reverie1988** [villagebully8/yybs#6]
![image](https://github.com/villagebully8/yybs/assets/102882768/d6f32aa1-66a8-4c9e-9809-a4af9f5cf3f8)

**Comment by drw2005** [comment]
![](https://ru.iytc.net/i/2024/06/26/rdcv4p.jpg)
## <font color=red>**我这边倒是能正常运行，但是有个建议，推送的信息能不能推送签到结果，而不是失败信息。现在接收的都是这样的，感觉没啥意义：**</font>
![](https://ru.iytc.net/i/2024/06/26/s8dm0p.jpg)

**Comment by reverie1988** [comment]
> ![](https://ru.iytc.net/i/2024/06/26/rdcv4p.jpg)
> 
> ## <font color=red>**我这边倒是能正常运行，但是有个建议，推送的信息能不能推送签到结果，而不是失败信息。现在接收的都是这样的，感觉没啥意义：**</font>
> 
> ![](https://ru.iytc.net/i/2024/06/26/s8dm0p.jpg)

我的问题，变量忘加#手机号#TOKEN了
